/*
(c) 2019 by dbj@dbj.org -- CC BY-SA 4.0 -- https://creativecommons.org/licenses/by-sa/4.0/
*/  
	#ifndef	DB_FILE_PATH_INC

	#define	DB_FILE_PATH_INC
	/* 
	local database taken from: 
	https://github.com/AyeshJayasekara/English-Dictionary-SQLite

	this database is required for dbjsqluser to work
	if your path is different please set it here
	*/
	using namespace std::literals ;

	constexpr inline auto DICTIONARY_DB_FILE_PATH = "d:\\dictionary.db" ;

	#endif //	DB_FILE_PATH_INC
